root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/SanityTranslator ."
bin = "tmp/SanityTranslator"
full_bin = ""
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
exclude_file = []
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_regex = []
exclude_unchanged = false
follow_symlink = false
delay = 1000
stop_on_error = true
send_interrupt = false
kill_delay = "0s"

[log]
time = true
level = "debug"

[misc]
clean_on_exit = true
